name: ci
permissions:
  contents: read
  pull-requests: write
on: pull_request
jobs:
  linting:
    strategy:
      matrix:
        python-version: ["3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run ruff linter
        run: |
          uv run ruff check .
  test:
    strategy:
      matrix:
        python-version: ["3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run pytest
        run: uv run pytest tests/ -v --tb=short
